# Документация NumPy

In [2]:
import numpy as np

### Квадратный корень

In [3]:
np.sqrt(19)

4.358898943540674

### Логарифм

In [4]:
np.log(10)

2.302585092994046

### Среднее арифмитическое

In [5]:
np.mean([20, 34, 56])

36.666666666666664

### Медиана

In [6]:
np.median([20, 34, 56])

34.0

### Создание массива

In [7]:
np.array([23, 35, 65])

array([23, 35, 65])

In [8]:
np.array([[23, 58, 34],
         [67, 81, 49]])

array([[23, 58, 34],
       [67, 81, 49]])

In [17]:
np.array([[0, 0, 1],
         [0, 1]], dtype='object')

array([list([0, 0, 1]), list([0, 1])], dtype=object)

In [11]:
np.array([['Ann', 'Kate'],
          [23, 24]])

array([['Ann', 'Kate'],
       ['23', '24']], dtype='<U21')

###  Создание массива от m до n

In [40]:
np.arange(2, 9)

array([2, 3, 4, 5, 6, 7, 8])

In [41]:
np.arange(2, 9, 3)

array([2, 5, 8])

In [42]:
np.arange(2, 9, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5])

### Создание массива из нулей

In [44]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Создание массива из едениц

In [45]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Создание еденичной матрицы

In [46]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Логический массив

In [49]:
ar1 = np.array([[15, 23, 32, 36, 52],
              [68, 34, 55, 78, 20],
              [25,  67, 33, 45, 14]])
ar1 >= 16

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [51]:
(ar1 >= 18) & (ar1 < 60)

array([[False,  True,  True,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False]])

### Умножение массивов

In [13]:
np.array([0.62, 0.48, 0.37]) * 100

array([62., 48., 37.])

### Деление массивов

In [15]:
np.array([0.62, 0.48, 0.37]) / 2

array([0.31 , 0.24 , 0.185])

### Сложение массивов

In [14]:
np.array([5, 7, 9]) + np.array([2, 4, 6])

array([ 7, 11, 15])

### Возведение в степень

In [16]:
np.array([5, 7, 9]) **2

array([25, 49, 81])

### Размерность массива

In [18]:
m = np.array([[2, 5],
             [7, 9],
             [4, 6]])
m.ndim

2

### Вид массива

In [19]:
m.shape

(3, 2)

### Число элементов

In [52]:
m.size

6

### Сумма всех элементов массива

In [55]:
m.sum()

33

### Произведение всех элементов массива

In [71]:
m.prod()

15120

### Обращение по индексу

In [22]:
m[1][1]

9

In [23]:
m[1, 1]

9

In [24]:
m[2]

array([4, 6])

### Срезы массива

In [25]:
m[0:2]

array([[2, 5],
       [7, 9]])

In [26]:
m[1:]

array([[7, 9],
       [4, 6]])

In [27]:
m[:1]

array([[2, 5]])

In [28]:
m[:]

array([[2, 5],
       [7, 9],
       [4, 6]])

In [30]:
m[0:3:2]

array([[2, 5],
       [4, 6]])

In [31]:
m[::2]

array([[2, 5],
       [4, 6]])

In [33]:
m[::-1]

array([[4, 6],
       [7, 9],
       [2, 5]])

### Минимум в массиве

In [35]:
marks = np.array([6, 7, 3, 4, 9, 35, 12])
marks.min()

3

### Минимум в массиве (индекс)

In [38]:
marks.argmin()

2

### Максимум в массиве

In [36]:
marks.max()

35

### Максимум в массиве (индекс)

In [37]:
marks.argmax()

5

### Изменить размерность массива

In [56]:
sc = np.array([3, 5, 7, 9,  8, 10])
sc.reshape(3, 2)

array([[ 3,  5],
       [ 7,  9],
       [ 8, 10]])

### Определить число измерений  массива

In [59]:
score = np.array([[ 3,  5],
       [ 7,  9],
       [ 8, 10]])
score.ndim

2

### Транспонирование массива

In [60]:
score.transpose()

array([[ 3,  7,  8],
       [ 5,  9, 10]])

### Преобразовать в одномерный массив

In [61]:
score.ravel()

array([ 3,  5,  7,  9,  8, 10])

### Округление значений массива

In [65]:
M = np.array([1.6787, 4.7003, 8.4453, 3.9385])
M.round(1)

array([1.7, 4.7, 8.4, 3.9])

In [66]:
M.round(2)

array([1.68, 4.7 , 8.45, 3.94])

### Округлить до целого числа в меньшую сторону

In [67]:
np.floor(M)

array([1., 4., 8., 3.])

### Округлить до целого числа в большую сторону

In [68]:
np.ceil(M)

array([2., 5., 9., 4.])

### Добавить число к каждому элементу

In [69]:
np.add(M, 2)

array([ 3.6787,  6.7003, 10.4453,  5.9385])

### Отнять число у каждого элемента

In [70]:
np.subtract(M, 1)

array([0.6787, 3.7003, 7.4453, 2.9385])

### Преобразовать массив в строку

In [90]:
ar1 = np.array([('Anna', 19, 168), ('Sam', 23, 180), ('Pam', 23, 180)],
                dtype = [('name', 'U10'), ('age', int), ('height', float)])
np.array2string(ar1)

"[('Anna', 19, 168.) ('Sam', 23, 180.) ('Pam', 23, 180.)]"

### Преобразовать в список

In [91]:
ar1.tolist()

[('Anna', 19, 168.0), ('Sam', 23, 180.0), ('Pam', 23, 180.0)]

### Формат даты  времени

In [74]:
d1 = "2022-05-01"
d2 = "2022-05-11"
np.datetime64(d1)

numpy.datetime64('2022-05-01')

###  Вычитание дат

In [75]:
np.datetime64(d2) - np.datetime64(d1)

numpy.timedelta64(10,'D')

### Структурированные списки

In [79]:
info = np.array([('Anna', 19, 168), ('Sam', 23, 180), ('Pam', 23, 180)],
                dtype = [('name', 'U10'), ('age', int), ('height', float)])
print(info)

[('Anna', 19, 168.) ('Sam', 23, 180.) ('Pam', 23, 180.)]


In [83]:
info['age'][0]

19

In [81]:
info['age']

array([19, 23, 23])

In [82]:
info[['age', 'height']]

array([(19, 168.), (23, 180.), (23, 180.)],
      dtype={'names':['age','height'], 'formats':['<i8','<f8'], 'offsets':[40,48], 'itemsize':56})

### Сохранение массива

In [84]:
np.save("info.npy", info)

In [88]:
ages = np.array([61, 73, 18, 92])
np.savetxt("ages.txt", ages)

### Загрузка  массива

In [86]:
new = np.load("info.npy")
new

array([('Anna', 19, 168.), ('Sam', 23, 180.), ('Pam', 23, 180.)],
      dtype=[('name', '<U10'), ('age', '<i8'), ('height', '<f8')])